version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "@octokit/rest"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
