description: GitHub Action that automatically merges Dependabot PRs
inputs:
  github_user:
    description: GitHub user supported by action. Defaults to dependabot[bot]
    required: false
    default: dependabot[bot]
  github_token:
    description: Token for action. Default method for authentication
    required: false
  github_app_id:
    description: GitHub App id
    required: false
  github_app_private_key:
    description: GitHub App private key
    required: false
  github_app_installation_id:
    description: GitHub App installation id
    required: false
  semver_match:
    description: major, minor or patch
    required: false
    default: patch
  reviewers:
    description: Reviewers to add to PR in case auto merge is not possible. Comma separated list
    required: false
  team_reviewers:
    description: Team reviewers to add to PR in case auto merge is not possible. Comma separated list
    required: false
name: Dependabot auto merge
runs:
  main: dist/index.js
  using: node16