name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Node.js version
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci --no-audit --no-progress --prefer-offline
      - name: Build
        run: npm run workflow:package
      - name: Update
        run: |
          git config user.email '{{ secrets.action_user_email }}'
          git config user.name '{{ secrets.action_user_name }}'
          git add .
          git commit -m "Updated action [skip ci]"
          git push
    timeout-minutes: 5
