name: Continuous Delivery

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Select Node.js version
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci --no-audit --no-progress --prefer-offline

      - name: Package action
        run: npm run package

      - name: Create tag
        run: |
          git config --global user.name '{{ secrets.MERGEBOT_USER_NAME }}'
          git config --global user.email '{{ secrets.MERGEBOT_USER_EMAIL }}'
          git add dist
          git commit -m "Update action"
          git push origin :refs/tags/'v${{ secrets.MERGEBOT_MAJOR }}'
          git tag -a 'v${{ secrets.MERGEBOT_MAJOR }}' -m "Update action" --force
          git push --tags
