name: Continuous Integration

on: 
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Select Node.js version
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci --no-audit --no-progress --prefer-offline
      - name: Run checks
        run: npm run workflow:test
      - name: Package action
        run: npm run workflow:package
      - name: Run action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        run: |
          git config user.email '{{ secrets.ACTION_USER_EMAIL }}'
          git config user.name '{{ secrets.ACTION_USER_NAME }}'
          git add .
          git commit -m "Update action [skip ci]"
          git push
