name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Select Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci --no-audit --no-progress --prefer-offline
      - name: Run checks
        run: npm run workflow:test
      - name: Package action
        run: npm run package
      - name: Run action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5
