name: Mergebot

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:

jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: e-conomic/mergebot@v1
        with:
         github_app_id: ${{ secrets.MERGEBOT_APP_ID }}
         github_app_private_key: ${{ secrets.MERGEBOT_PRIVATE_KEY }}
         github_app_installation_id: ${{ secrets.MERGEBOT_INSTALL_ID }}
         team_reviewers: "platform"
         semver_match: minor
