name: Dependabot auto merge

on:
  check_suite:
    types:
      - completed
  workflow_dispatch:

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: e-conomic/mergebot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ secrets.PLATFORM_REVIEWERS }}
          semver_match: minor
